XRTK/com.xrtk.core

XRTK-Core/Assets/XRTK/Inspectors/MixedRealityPreferences.cs
**Overview**
Unity recommends to update to the new SettingsProvider:
`Assets\XRTK\Inspectors\MixedRealityPreferences.cs(124,10): warning CS0618: 'PreferenceItem' is obsolete: '[PreferenceItem] is deprecated. Use [SettingsProvider] instead.'`
No functional changes.
=> Updated PreferenceItem to SettingsProvider

XRTK-Core/Assets/XRTK/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
**Overview**
Fixes an issue where not the specific mapping profile but the BaseMixedRealityProfile is created when clicking the "create" button in config UI.
Solves parts of: https://github.com/XRTK/XRTK-Core/issues/19
=> Fix create new controller mapping profile

XRTK-Core/Assets/XRTK.SDK/Features/UX/Scripts/Utilities/Billboard.cs
**Overview**
Billboard script did not automatically use the Camera due to private field usage instead of getter.
=> Fix to use TargetTransform Getter in update to get camera in first run

XRTK-Core/Assets/XRTK/Utilities/Solvers/ControllerFinder.cs
**Overview**
When implementing a custom controller without a visualizer (Keyboard controller) a NRE occurred in check when accessing GameObjectProxy
**Breaking Changes:**
- nothing
=> Fix NRE when custom controller implementation does not have a visualizer

XRTK-Core/Assets/XRTK.WindowsMixedReality/Controllers/WindowsSpeechDataProvider.cs, XRTK-Core/Assets/XRTK.WindowsMixedReality/SpatialObservers/WindowsMixedRealitySpatialMeshObserver.cs
Ensures that services that use a uwp component are setting them when they're constructor is called in the editor, which then updates the player settings.
When the Mixed Reality Toolkit instance is created all services get their constructors called, even at edit time.
=> Services that utilize uwp capabilities, now properly set them

XRTK-Core/Assets/XRTK/Inspectors/MixedRealityToolkitInspector.cs, XRTK-Core/Assets/XRTK/Inspectors/Utilities/ChannelPackerWindow.cs, XRTK-Core/Assets/XRTK/Inspectors/Utilities/MixedRealityInspectorUtility.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/BuildDeployWindow.cs
- Sorted menus![image](https://user-images.githubusercontent.com/13334553/55451233-f1125580-5586-11e9-83fa-4178fbef3569.png)
- Removed pesky popup when no profiles exist, instead there's now a button under the empty profile slot on the main toolkit GameObject.
=> Menu Organization

.gitignore, .gitmodules, XRTK-Core/Assets/SymbolicLinkSettings.asset, XRTK-Core/Assets/XRTK/Inspectors/Utilities/GitUtilities.cs, XRTK-Core/Assets/XRTK/Inspectors/Utilities/Packages/MixedRealityPackageInfo.cs, XRTK-Core/Assets/XRTK/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs, XRTK-Core/Assets/XRTK/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Packages/manifest.json
There was an issue with the core package pulling in the subodules into the package of other projects.
Linked to a unity bug, but added a temp hackaround to solve the problem in the short term.
Also fixed a new small bugs:
- batch mode debugging was overwriting the local setting, now properly xor the flag
- ensured we were syncing after updating submodules
- minor formatting changes.
=> Dev package fixes

XRTK-Core/Assets/XRTK/Inspectors/Utilities/AutoSceneSwitcher.cs
When pulling a project, team members didn't get the base/start scene set as their `MixedRealityPreference.StartSceneAsset`. This ensures everyone that pulls the repository starts with the same scene.
=> Sets the start scene on load

XRTK-Core/Assets/XRTK/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
Sometimes symbolic links aren't created properly when switching branches and the editor doesn't trigger a domain reload
=> added DidReloadScripts attribute to RunSync to cover more edge cases

XRTK-Core/Assets/XRTK/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs, XRTK-Core/Assets/XRTK/Services/MixedRealityToolkit.cs
- Removed the profile check for the spatial awareness data provider's profiles, that should be handled in the constructor of the respective data provider with a thrown exception if missing.
- Moved the type null checks until after the platform check to better support false positive errors thrown when that type/assembly is probably missing because we're targeting a different platform.
- updated `TypeRefPropertyDrawer` to not throw an error if the type is missing because we're targeting a different platform.
=> More robust cross platform support

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Packages/com.xrtk.core/package.json
Just because a folder exists doesn't mean that the link is valid. So we pass back the validity results and use that in our next step in the linker sync loop.
=> Fixed an issue where link validation was failing

XRTK-Core/Assets/XRTK.Tests/InputSystem/TestFixture_02_InteractionDefinitionTests.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs
When an inverted `Vector2` axis is checked, it's not properly flagged as changed.
I've updated the unit tests to properly test against this case for future changes.
=> Fixed inverted change check for vector2 interaction mapping

XRTK-Core/Assets/XRTK.Tests/InputSystem/TestFixture_02_InteractionDefinitionTests.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/BoundsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/MixedRealityInputSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/TeleportSystem/MixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/InputMappingAxisUtility.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/Interpolator.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/TwoHandMoveLogic.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Rendering/ClippingPlane.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Rendering/ClippingSphere.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/ConstantViewSize.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/InBetween.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/Solver.cs
- Also includes other misc perf fixes
=> cleaned up Vector2 interaction mapping with faster code

XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/FocusProvider.cs
- ensure our nearClipPlane is set correctly instead of just asserting about it
=> Set nearclip plane for UI raycasting

XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/ControllerMappingLibrary.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/ControllerPopupWindow.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityStandardShaderGUI.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityControllerMappingProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerMappingProfilesInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityNetworkSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwareness/BaseMixedRealitySpatialMeshObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwareness/BaseMixedRealitySpatialObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwareness/BaseMixedRealitySurfaceObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwareness/MixedRealitySpatialAwarenessSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
This PR covers the required changes to all of the profile inspectors to enable them to not require the Service Locator object be setup and initialed in the scene to configure them.
- Core
All references to the `MixedRealityToolkit.Instance` have been removed for the most part and replaced with a dynamic profile reference.
This will require the profiles to have to be setup at least once in the main configuration profile to get these reference properly set.
- Fixes: #76
=> No longer require the service locator to configure profiles

XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs
Fixes absolute path finding by adding `Pacakges/` prefix to the directory path check.
- Fixes: #166
- updated WMR submodule checkout
- updated SDK submodule checkout
=> fixed absolute path finding

XRTK-Core/Packages/com.xrtk.core/Utilities/CameraCache.cs
Minor fix that makes sure to add the AudioListener component to a newly created Main Camera Game Object. Removed if block that would never run.
- Core
- Fixes #163.
- Add AudioListener component to Main Camera game object if it is created by XRTK
=> Add audio listener when creating a new Main Camera game object

XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Fixes finding msBuild for 2019+
=> Fixed the path for finding msbuild for 2019+

XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityProfile.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Makes the parent profile property more dynamic.
- Fixes: #176
=> don't serialize the parent profile, as they're actually dynamic.

XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs
Adds an additional `GameObject` extension to help set renderers, graphics and colliders active or inactive without setting the `GameObject` itself inactive so that scripts still run on them, but they're effectively disabled to the input system.
=> Added SetRedneringActive game object extension

XRTK-Core/Packages/com.xrtk.core/Services/BaseEventSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Async/Awaiters.cs
Needed the ability to wait indefinitely.
- Extension
=> Updated Awaiter.WaitUntil extension method with indefinite option

XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/SupportedPlatforms.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Solves #187.
- Added Android and iOS as selectable Targets for supported platforms when configuring components and services
=> Add Android and iOS targets to supported platforms

XRTK-Core/Assets/csc.rsp, XRTK-Core/Assets/csc.rsp.meta, XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/ControllerMappingLibrary.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/MixedRealityPose.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/BoundsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/MixedRealityInputSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/InterpolationUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/RadialView.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs
- ported deadzone fixes
- enabled warnings as errors
- misc formatting updates
=> Ports and formatting

XRTK-Core/Packages/com.xrtk.core/Extensions/CanvasExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/FastSimplexNoise.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/Importers/GltfEditorImporter.cs
Cleaned up the warnings as error problems and fixed a bug with a GameObject extension
- Added null assets to fix the warnings as errors thought out solution.
- Fixed a bug in the SetChildrenActive GameObject extension
=> Warnings as errors cleanup

XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/TransformExtensions.cs
Adds a way to easily find the common root of two GameObjects or Transforms. Will be used in subsequent changes to the event routing.
- Extension
=> Find common root for GameObject and Transforms

XRTK-Core/Packages/com.xrtk.core/Inspectors/XRTK.Inspectors.asmdef, XRTK-Core/Packages/com.xrtk.core/XRTK.asmdef
Pre-resolves an issue in 2019.2 whereby the UI system has been moved out of the editor in to a package.
Confirmed adding this reference (even though earlier versions don't recognise it) does not impact operation.
Adds an asmdef reference to the Unity.ugui package in the Core / Inspectors definitions
=> Unity 2019.2 Pre-Fixes

XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/GenericOpenVRController.cs
Adds proper support for the Vive Pro in the generic open vr controller mapping
=> Added Vive Pro controller mapping support

XRTK-Core/Packages/com.xrtk.core/Utilities/Rendering/ClippingPrimitive.cs
Added a few convenience methods to the base clipping plane component
=> clipping plane component updates

XRTK-Core/Packages/com.xrtk.core/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Adds a convince method to the `SpatialAwarenessSystem` to change the mesh visibility for all spatial observers.
=> Added SetMeshVisibility convenience method to SpatialAwarenessSystem

XRTK-Core/Packages/com.xrtk.core/Extensions/TransformExtensions.cs
Added transform extension to set all colliders active in self and descendants
- Extension
=> Added transform extension to set all colliders active

XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityPreferences.cs
When no scenes are in the editor build settings the preferences window wasn't allowing me to set the scene I wanted in the XRTK start scene object inspector. This PR should fix this if no scenes are present.
This PR may also fix #174 but needs to be tested.
=> Ensure we set the scene in the build settings if no scenes are available

XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/CardinalAxis.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/CardinalAxis.cs.meta, XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/FlattenMode.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/FlattenMode.cs.meta
Added additional enum definitions for cardinal axis and flattening mode.
- To be used with BoundingBox but possibly other uses.
=> Added CardinalAxis and FlattenMode enum definitions

XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Removed:
* StandaloneLinux
* StandaloneLinuxUniversal
Platforms as they have been deprecated in 2019.2.  StandaloneLinux64 remains for Linux systems
- Resolves: #268
=> Platforms cleanup

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs
fix to resolve #300, properly sorts the tag versions returned by Git based on a 3 digit version code.  Select the actual latest version based on:
x.x.x version number
Previously, last was determined by the double value parsed value, which is incorrectly sorted by .NET.  Now sorts by each individual version identifier to locate the latest.
Updates Git Tag version sort to sort by each individual version identifier
- Fixes: #300
=> Fix to resolve Git Tag sorting issue #300

XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs
Fixed a warning when forcing the asset database to refresh during reload. This may or may not fix the first time startup crash we're seeing but worth a test.
- Fixes: Don't force refresh of asset database during startup, per warning from Unity Editor.
=> Fixed a warning during first start

XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs
Resolves issue with WMR OpenVR grip and updates axis data from Unity input to use raw data for precision
=> OpenVR controller update

XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs
Fixed the ambiguous interaction mapping constructors.
- Fixes: #345 
- Fixes: #336
- Supersedes: #346 
- Update the `MixedRealityInteractonMapping` constructors but afaik the Oculus package is the only one taking advantage of it atm.
=> Fixed the ambiguous interaction mapping constructors

XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/IMixedRealityControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Speech/WindowsDictationDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityJoystickDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/package.json
Update OpenVR platform to use new Interactions Mapping Extension
- Updated all controller data providers to use new Interaction Mapping Extension
- Cleaned up and refactored the controller and controller data providers to be more concise.
Changes to the Controller interfaces will break the other platforms, update required
- `IMixedRealityControllerDataProvider.GetActiveControllers()` was replaced with `IMixedRealityControllerDataProvider.ActiveControllers`
- `IMixedRealityInteractionMappingExtensions` was consolidated into a single method call.
Changes extracted from @StephenHodgson PR for InputActions #358
=> Cleaned up controller data providers

XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs
Throwing errors for setting float data on digital axis. Part of the changes in #363
- Fixed error checking for axis type.
=> Should be able to use digital axis type when setting float data

XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Parented the SpatialAwarenessParent under the playspace to ensure that the spatial mesh stays in the same place when teleporting
- Moved the Spatial Awareness system's root GameObject reference under the Playspace.
=> Updated Spatial Awareness Parent Object Transform to fix teleporting

XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
There was one use case for the `PlatformUtility` flags that wasn't covered. Where we only want a service to run in the editor only on any platform.
| Figure | Editor | Rumtime |
|---|---|---|
| 1 | X | |
| 2 | X | X |
| 3 | | X |
1. This should **always** run in the editor regardless of the target build platform but never the build:![image](https://user-images.githubusercontent.com/13334553/65984542-ff65ff00-e44d-11e9-8871-a0c34ebbab82.png)
2. This should run in the editor && build if the build target **IS** enabled:![image](https://user-images.githubusercontent.com/13334553/65984558-08ef6700-e44e-11e9-836f-0b7895db785d.png)
3. This should **never** run in the editor and only runs on the build:![image](https://user-images.githubusercontent.com/13334553/65984700-4eac2f80-e44e-11e9-955b-bb31 …
=> Ensure we always start a service if only the editor flag is set

XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/TrackedObjectType.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs
Added the ability to specify the body (the mixed reality playspace) as a tracked object to solve the position and rotation against. Used for body locked solvers.
- Renamed `TrackedObjectType.MotionControllerLeft` to `TrackedObjectType.LeftHandOrController`
- Renamed `TrackedObjectType.MotionControllerRight` to `TrackedObjectType.RightHandOrController`
=> Added body tracking to solver handler

XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs
Fixed prefab attribute to ensure that devs know to use `GameObject` field types with it.
Sometimes when upgrading a field with specific type to have a `PrefabAttribute` devs don't get an error about having to also change the field type to `GameObject`.
=> Fix prefab attribute

.github/FUNDING.yml, XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityCameraProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/TrackedObjectType.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityCameraRig.cs.meta, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/DefaultCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/DefaultCameraRig.cs.meta, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/TeleportSystem/MixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/Orbital.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs
After updating the solvers in the last PR I did, I realized that I didn't actually make the solvers body locked but playspace locked. This PR aims to correct the body locking features by extending the `IMixedRealityCameraSystem` to include options for a `IMixedRealityCameraRig` that can be implemented on a `MonoBehavior` and used to reference the camera rig components and transforms.
- Fixes: Body Locked/Playspace Locked behavior in the solver system.
- Added a few new component types to the `IMixedRealityCameraSystem`:
- `IMixedRealityCameraRig` which keeps track of the playspace, camera, and body transforms.
- `MixedRealityCameraProfile` now has two …
=> Initial changes for the new camera rig configuration

XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs
Added `XR.XRDevice.isPresent` to the `IMixedRealityCameraSystem.IsStereoscopic` check.
=> Also checks if an xr device is present for stereoscopic check

XRTK-Core/Packages/com.xrtk.core/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityCameraProfile.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/DefaultCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/TeleportSystem/MixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/CameraCache.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/Orbital.cs
Fixed the errors from the camera rig shutting down improperly and syncing the playspace and bodypace transforms correctly.
Mainly we wanna ensure that the body is roughly the same position/rotation of the head (within the adjustment angle threshold)
- Fixed #404 component casting check to ensure we're not trying to destroy components that aren't a IMixedRealityCameraRig type.
- Added flags to check if app was quitting before setting up objects when we're trying to cleanup.
- Reverted some changes where we were parenting to the body instead of the playspace.
- Reverted changes where we were moving the PlaySpace improperly.
- Added appropriate fallbacks to …
=> Fixed a few things with the new camera rig

XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityExtensionServiceProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/NetworkingSystem/MixedRealityNetworkSystemProfile.cs, XRTK-Core/Packages/com.xrtk.core/EventDatum/Input/BaseInputEventData.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/EnumerableExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/EventSystem/IMixedRealityEventSystem.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityService.cs, XRTK-Core/Packages/com.xrtk.core/Services/BaseEventSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/BaseServiceWithConstructor.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/package.json
Broke out a few of the braking changes from the Diagnostics PR.
Mainly this is just a cleanup pass.
Some of the biggest changes:
- Updated the `MixedRealityToolkit` service registration to no longer check if a profile is null, as these services require the profiles they're checking. (in fact the `IsServiceEnabled` flag is typically bundled with this profile null check anyway.)
- updated a few of the headers to be XRTK as they're probably nothing like the MRTK counterpart.
- Misc formatting and style changes.
- naming
- accessors
Are there any breaking changes included in this change that would prevent or cause issue for existing projects.
- `IMixedRealityBaseEventSystem.EventListeners` is now a readonly type: …
=> broke out the changes from the diagnostics PR

XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityMemoryDiagnosticsDataProvider.cs
XRTK - Mixed Reality Toolkit Change Request
Fixed the issue with the diagnostics data provider not reporting the correct memory limit
- Fixes: #437
=> Fixed diagnostics data provider memory limit reporting

XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/IMixedRealityController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs
Pulling `SetupConfiguration` and `TryRenderControllerModel` into `IMixedRealityController` since those two have proven to be needed in the interface when working with different kinds of controllers.
- Core
=> Pull BaseController methods to interface

XRTK-Core/Packages/com.xrtk.core/Utilities/WindowsApiChecker.cs
Fixes a copy paste error in the `WindowsApiChecker` which led to API v7 and v8 always being `false`
- Core
=> Fix copy paste error in windows api checker

XRTK-Core/Packages/com.xrtk.core/Services/BaseEventSystem.cs
Base event system has a local variable that wasn't properly being used.
=> just a little tweak to use the existing local variable

XRTK-Core/Packages/com.xrtk.core/Extensions/TransformExtensions.cs
I was having performance issues in my app when using the bounding box and manipulation handlers. I was able to narrow this down to a bounds calculation we were calling in each update loop.
See https://github.com/XRTK/SDK/pull/130
- Extension
- updated `Transfrom.GetColliderBounds` to reference the colliders it's using to get the bounds
- Added another `Transform.SetCollidersActive` override extension method that also uses a reference to the colliders used
- `Transfrom.GetColliderBounds` now requires you pass in a `ref` to the colliders you want to calculate the bounds for.
=> Transform Extension Collider and Bounds Calculation Performance Update

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Adds a simple utility to draw a capsule wire gizmo as seen when working with capsule colliders.
=> Add a utility to draw a capsure wire gizmo

XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs, XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_03_ExtensionsTests.cs, XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_03_ExtensionsTests.cs.meta, XRTK-Core/Packages/com.xrtk.core/Extensions/ArrayExtensions.cs
* Added new "InitialiseArray" array extension to set all values of an array to a new value, including Tests
* Added null check on Array AddItem
* Fixed license in Core test 2
=> New array Extension plus tests

XRTK-Core/Packages/com.xrtk.core/Extensions/ArrayExtensions.cs
Added a remark to the ArrayExtensions ArrayInitialise function, to ensure devs are aware to only use value types, such as structs.  Reference types will have adverse effects if used incorrectly.
=> Added a remark to the ArrayExtensions ArrayInitialise function

XRTK-Core/Assets/XRTK.Tests/Services/ITestDataProvider1.cs, XRTK-Core/Assets/XRTK.Tests/Services/ITestExtensionServiceProvider1.cs, XRTK-Core/Assets/XRTK.Tests/Services/TestExtensionService1.cs, XRTK-Core/Assets/XRTK.Tests/Services/TestExtensionServiceProvider1.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityExtensionServiceProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityExtensionServiceProfile.cs.meta, XRTK-Core/Packages/com.xrtk.core/Extensions/TypeExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/TypeExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Services/BaseExtensionService.cs
The new configurations inspector depends on generic type args to be found in order to correctly derive the "Instanced Type" selectable values. Currently it will only look for those on the base type of the profile selected, this PR adds a recursive lookup for generic type args to solve that problem.
=> Fixes to correctly filter for nested services/data providers in the new configuraitons inspector

XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/UniversalWindowsPlatform.cs
Fixed the preprocessor directive for the Universal Windows Platform. The used one `UNITY_UWP` will run even when in editor and thus services will run even if the `Editor` platform was not configured.
=> Fix wrong UWP preprocessor directive

XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs
Implemented a simple approach to move the camera to the default head height position configured in the profile, when not XR device is attached.
- Fixes: #487
=> Make use of DefaultHeadHeight setting in editor

XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/GenericOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusRemoteOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveKnucklesOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveWandOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/XboxController.cs
Removes the obsolete `SetupDefaultInteractions` in `BaseController` since it's not run anywhere anymore.
=> Remove obsolete SetupDefaultInteractions

XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandController.cs
Adds a default interaction mapping for hand controllers.
=> Create default hand interaction for spatial pointer pose

XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
Pulled out some more changes related to #517 
- Race condition in #517 where the boundary visualizations were trying to use the camera rig before the system had finished setting up. Moved the boundary visualization from Initialize to Enable, which makes sense anyway cause if we disable or enable this system we'd expect the visualizations to also toggle on/off.
=> updated boundary system to utilize enable and disable properly

XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/ScriptableObjectExtensions.cs
- Changes path to be relative to the project if a full path is provided
=> Updated ScriptableObject.CreateAsset method to handle full path names

XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
The Boundary system's floor GameObject should likely have been parented under the `BoundaryVisualizationParent` like all the rest of the generated boundary content.
=> fixed an unparented boundary game object

XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/BasePlatform.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/CurrentBuildTargetPlatform.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityPlatform.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Added a way to define platform overrides that will effectively disable any available platforms if another is overriding it. Will be used for `OculusPlatform` definition.
=> Added platform overrides

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs
=> Added configuration foldout to all service configuration profiles

XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityServiceProfile.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
The configuration profiles were not properly registering their data providers because of a type casting bug where the  more derived interface types were getting passed on and this caused the check `is` to fail when attempting to cast the configuration profile to `BaseMixedRealityServiceProfile<IMixedRealityDataProvider>`
Adding the contravarent `IMixedRealityServiceProfile<out TService>` solves this problem.
We should probably have been using the interfaces in the service locator anyway instead of our concrete types for the profiles anyway.
=> Added IMixedRealityServiceProfile<out TService>

XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PlatformEntryPropertyDrawer.cs
Updated the label for the EditorBuildTarget platform to say `Editor + Build Target`. It's a small change but IMO better indicates that this means runs in editor when the build target matches.
=> Update EditorBuildTarget enum for better understanding

XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityToolkitRootProfile.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/EditorGUILayoutExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/EditorGUILayoutExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/SerializedPropertyExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/SerializedPropertyExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityCameraDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/DiagnosticsSystem/MixedRealityDiagnosticsSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitRootProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySpatialMeshObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySpatialObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySurfaceObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProviderInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Lines/DataProviders/BezierDataProviderInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Lines/DataProviders/SplineDataProviderInspector.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Lines/DataProviders/BezierLineDataProvider.cs
Just adds an inspector extension / utility to render a foldout with a bold label easily, like in many standard Unity inspectors. Also updates all the inspectors (except input system, since that one is currently under construction in other PRs).
=> Implement FoldoutWithBoldLabel inspector utility and update inspectors

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraSystemProfileInspector.cs
Global profile object field was being rendered twice. Updated to use property foldout extension method.
=> fixed duplicate global profile entry in the camera system profile inspector

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/CanvasEditorExtension.cs
Fixes the issue of a `CanvasUtility` being removed from a GameObject/Prefab without the user's consent. The utility will only get removed from a game object if
- The user answers No in the dialog prompt
- The user answers Never in the dialog prompt
This "fix" may lead to a `CanvasUtility` staying on a canvas that was set to Screen Space or modified in a way that it doesn't need a utility anymore. Or XRTK got removed from the scene or something. But that's better than having the user wonder why something stopped working because for some reason the utility got removed from his canvas.
=> Fix canvas utility removed from prefabs unintentionally

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs.meta
To prevent asset collisions and problems when copying prefabs and profiles, I thought it'd be best to regenerate any guid references in the copied assets.
=> Added guid regeneration for installed package profiles to prevent asset collisions

XRTK-Core/Assets/XRTK.Seed/PackagePickerWindow.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Editor/MixedRealityEditorSettings.cs
Because `Mixed Reality Toolkit/List Packages` menu is a part of the seed it's availible in the xrtk.core project, but we don't want people to install the packages as they're already referenced as submodules. 
To prevent this I added a simple XRTK key to check if the editor prefs has an XRTK key and disables the `Add selected packages` button to prevent its self destruction in the core project itself.
=> Disabled package installation button in xrtk.core project

XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs
Assigning any profile by dragging and dropping the object from the project window into the object slot was not working, as well as using the object picker, or cloning.
=> Fixed a bug where profile field assignment was not working

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/OpenVR/OpenVRControllerDataProvider.cs
Fix to add additional resolution of Oculus Controllers following the V16 firmware Oculus update (controllers renamed for Quest)
Adds an additional name lookup for Oculus based OpenVR controllers
=> Update OpenVR for Oculus Quest controller name change

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/Handedness.cs
This enum wasn't working with the `EnumFlagsAttribute` properly because of the `byte` type didn't provide enough data to properly mask the bits with `-1`. Updated the type size to be whatever the default is.
=> Updated handedness to properly work with the enum flags attribute

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityToolkitRootProfileInspector.cs
Fixes an issue where the "There is no active Mixed Reality Toolkit in your scene! Would you like to create one now?" dialog endlessly blocks the editor when pressing "Later".
To observe the error in dev open a scene without the Toolkit in it, e.g. some scene you want to load in additively when running. While in that scene select the MixedRealityToolkitRootProfile asset. The dialog shows up. Press later, press later, press later, press later...
Clear selection for one frame if the user answers "Later". That will make sure Unity does not trigger the `OnEnable` event right away again after selectin "Later".
=> Fix endless configure toolkit dialog issue

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/HandTrackedPoseProcessor.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/MixedRealityHandController.cs
- updated tracked pose processor compare
- aesthetic and spell checking in hand controller
=> Misc changes to pose processor and hand controller

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/TypeExtensions.cs
I noticed that when the system failed to find a valid type perf would get a serious hit in the editor, and quickly realized we could optimize the type lookup.
This PR aims to fix the perf regression and further optimize the type lookup by guid.
=> optimized perf when looking up types by guid

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/QuaternionExtensions.cs
As requested pulled out `Quaternion.Approximately` extension from the hands PR.
It is a utility to decide whether two rotations are roughly the same.
https://github.com/XRTK/XRTK-Core/pull/552/files#r432893807
=> Pull out Quaternion.Approximately from hands PR

XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Textures/xrtk_logo_transparent_square.png.meta
Fixed the [build warnings](https://dev.azure.com/xrtk/Mixed%20Reality%20Toolkit/_build/results?buildId=5039&view=logs&j=0ab14b9f-e499-56d5-97b1-fd98b70ea339&t=88e774dc-252d-5c6d-8529-f86a4aebeef7&l=1130) from the xrtk logo for Android platform
=> fixed android build warnings about the logo

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Fixes the issue reported by @SimonDarksideJ in the hands PR https://github.com/XRTK/XRTK-Core/pull/552
```
Simulated Hands inspector spams console if looked at in runtime
Replication Steps:
Open Demo Scene
Run on any platforms
Select the MRT Game Object
Navigate to "Input System profile"
Expand / touch the IMixedRealityInputDataProvider list
See error SPAM
Error Details
Object reference not set to an instance of an object
at XRTK.Providers.Controllers.Simulation.BaseSimulatedControllerDataProvider.RefreshSimulatedDevices () [0x00001] in C:\LocalDevelopment\XRTK-Core\XRTK-Core\Packages\com.xrtk.core\Runtime\Providers\Controllers\Simulation\BaseSimulatedControllerDataProvider.cs:129 
at XRTK.Providers.Controllers.Simulation.BaseSimulatedControllerDataProvider.Update () [0x00008] in …
```
=> Fix profiles reset and services reinitialized when already running

XRTK-Core/Packages/manifest.json
Package changelog:
`Update remoting plugins to version 2.1.3.`
This also most likely fixes the a workaround currently found in `WindowsMixedRealityMotionController`
- Updated the wmr package
=> Update legacy WMR UPM package to 1.0.21

XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/CameraSystem/IMixedRealityCameraDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
Introduced 
```
/// <summary>
/// Is the head height, and thus the camera y-position, managed by the device itself?
/// If true, the <see cref="DefaultHeadHeight"/> setting is ignored and has no effect
/// on camera positioning.
/// </summary>
bool HeadHeightIsManagedByDevice { get; }
```
to `IMixedRealityCameraDataProvider` and implemented as
```
/// <inheritdoc />
public virtual bool HeadHeightIsManagedByDevice => XRDevice.isPresent;
```
in `BaseCameraDataProvider`
to only apply the `DefaultHeadHeight` setting, if the device does not manage head height itself, which is the case
with many devices, like HoloLens e.g.
By default we will assume as soon as an XR Device is connected that it manages head height, since most devices these days will do. The developer has the option to override …
=> Only apply default head height if not managed by device

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Resolves the errors when exiting playmode in the editor for the Windows Universal Platform.
Fixed a script reference in the SDK that improperly pointed to the LuminSpatialObserverProfile
- Fixes: https://github.com/XRTK/WindowsMixedReality/issues/97
- [SDK](https://github.com/XRTK/SDK/pull/198)
=> Fixed issues around errors when starting and stopping playmode in editor

XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAccessor.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAnimationChannelTarget.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAnimationSampler.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfBufferView.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfCamera.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfMeshPrimitive.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfSampler.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Serialization/GltfConversions.cs
Ported fix from MRTK, where it was noted there were serialisation issues with the gLTF importer when using the Unity JsonUtility
Mainly enums have been updated to use the ISerializationCallbackReceiver with a Serialization text field and the internal enum
Tested and noted the changes did improve serilization
=> Fixing gltf serialization

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/BaseHandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/HandBoundsLOD.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/HandBoundsLOD.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Simulation/Hands/SimulatedHandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/Controllers/Hands/IMixedRealityHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/BaseHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/MixedRealityHandController.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs
As per https://github.com/XRTK/XRTK-Core/issues/645 I renamed the `HandBoundsMode` enum so people understand what it's about. Just a minor tweak.
- Renamed `HandBoundsMode.Hand|.Fingers` to `HandBoundsLOD.Low|.High`
- [SDK](https://github.com/XRTK/SDK/pull/200)
- [Examples](https://github.com/XRTK/Examples/pull/15)
=> Rename HandBoundsMode to HandBoundsLOD for better understanding

XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MinPropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MinPropertyDrawer.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/CameraSystem/BaseMixedRealityCameraDataProviderProfile.cs
- added checks for near clips values in the camera data provider to prevent them from being set to zero
- updated all submodules
- Fixes: https://github.com/XRTK/WindowsMixedReality/issues/93
=> Fixed min attribute. now properly clamps min value in inspector

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Tests/Core/TestFixture_01_MixedRealityToolkitTests.cs, XRTK-Core/Packages/com.xrtk.core/Tests/InputSystem/TestFixture_03_InputSystemTests.cs, XRTK-Core/Packages/manifest.json, XRTK-Core/Packages/packages-lock.json
- Disable and destroy all services as soon as we get the quitting event
- Properly use `nameof`
- Fixed manifest
=> updated playmode/editor mode change transitions

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/BaseService.cs
There was a missing virtual keyword in one of the base implementations in `BaseService`
=> Fix missing virtual keyword for OnApplicationPause in BaseService

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs, articles/00-GettingStarted.md, articles/04-KnownIssues.md, articles/toc.yml
Since the move to place the default profiles and prefabs for all the various platforms to HIDDEN folders, there isn't actually a need to regenerate the GUID's for copied assets by default.
This ensures that any references between packages are retained as the asset guids remain unchanged when copied to a project's asset folder. And since the originals are in hidden folders, there is no conflict anymore.
The facility remains should it be needed, it is simply now OFF by default
Following discussions, the following changes were agreed (following on from PR #717 
- Fixes: #706
Tested in a new project without issue and previous referencing issues are no longer a problem.
=> Misc fixes for GUID regeneration issues

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityTeleportSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityTeleportSystemProfileInspector.cs.meta, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityToolkitRootProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/MixedRealityToolkitRootProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem/MixedRealityTeleportSystemProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem/MixedRealityTeleportSystemProfile.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/Handlers/IMixedRealityTeleportComponentHandler.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/Handlers/IMixedRealityTeleportComponentHandler.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/Handlers/IMixedRealityTeleportHandler.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/IMixedRealityTeleportDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/IMixedRealityTeleportDataProvider.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/IMixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/MixedRealityTeleportSystem.cs
This PR fixes https://github.com/XRTK/XRTK-Core/issues/504 and introduces some new features to the teleport system.
The core change is that the act of "teleporting" is now done by "teleportation handlers". Instead of the teleport system just moving the camera around. Using a new teleport system profile the user can configure a handler implementation to use, this opens up endless possibilities to handle teleportation.
Previously:
- Teleport just moves the camera/playspace to target position instantly. That's it
Now:
- You can either just teleport or have e.g. an animation / sound or whatever play when teleporting. It's all up to how the handler implements it
The PR comes with two default implementations.
This is what we had so far in terms of looks and behaviour. The user selects a …
=> Teleport System v2

.gitignore, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityTeleportSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem/MixedRealityTeleportSystemProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/MixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/TeleportMode.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/TeleportMode.cs.meta
This PR introduces `TeleportMode` to the teleport system and fixes https://github.com/XRTK/XRTK-Core/issues/725
Teleport Mode has two options:
- Default: The teleport system will instantly teleport the user to the selected location. This mode works out of the box and is the toolkit's default. This mode also works without SDK
- Provider: In provider mode the teleport system will not teleport the user itself but instead attach a teleport provider to the camera game object. Teleport providers can be customized and implemented using the `IMixedRealityTeleportProvider` interface. SDK has a `BaseTeleportProvider` for users to get started implementing their own provider. SDK also comes with a `FadingTeleportProvider` as an example of fully implemented teleport provider
- The teleport system …
=> Teleport Mode for Teleport System

XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Shaders/XRTK_Wireframe.shader
This is an attempt to fix the Wireframe shader error when building Android / Oculus projects.
I did test and it seemed to fix the issue.
=> Attempt to fix wireframe shader

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
This PR fixes the issue where with OpenVR the user would appear way above the ground when anything else than 0 was configured for the "HeadHeight" in the camera data provider profile.
The issue was in `BaseCameraDataProvider`. The "ApplyHeadHeight" method runs even in editor mode. And since in edit mode `XRDevice.isPresent` will always return `false`, the artifical head height is applied to the `TrackedPoseDriver` on the camera. Then when the application is run, it wasn't being reset back to 0f once the device tracking kicks in.
=> Fix camera / head position appears way above ground for OpenVR

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Fix to resolve issue where an error is generated if the MixedRealityToolkit is selected when a configuration is applied.
- Fixes #731 Updated package installer to clear the currently selected GameObject when applying configuration
=> Fix to resolve issue where an error is generated if the MixedRealityToolkit is selected when a configuration is applied.

XRTK-Core/Packages/com.xrtk.core/Editor/EditorActiveProfileChangeHandler.cs
Fixes the NREs thrown in the build's test steps when no active profile was configured for the toolkit.
NREs were thrown in the handler if no active profile was set.
=> Fix NRE in EditorActiveProfileChangeHandler

XRTK-Core/Packages/com.xrtk.core/Editor/EditorActiveProfileChangeHandler.cs
fixed a bug where the xrtk would auto-configure itself bc the Instance was called
- Fixes: #758
=> Fixed auto-configuration without user input

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/RenderPipeline.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/RenderPipeline.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/RenderPipelineUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/RenderPipelineUtilities.cs.meta
Adds a small utility class to detect the render pipeline currently in use.
=> Implement utility to check for used render pipeline

XRTK-Core/Packages/com.xrtk.core/Editor/Data/Controllers/Hands/HandControllerPoseProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/Hands/BaseMixedRealityHandControllerDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/Simulation/SimulatedHandControllerDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/MixedRealityInputSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/BaseHandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Simulation/Hands/SimulatedHandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/HandDataPostProcessor.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/HandGripPostProcessor.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/packages-lock.json
This PR addresses https://github.com/XRTK/XRTK-Core/issues/665 and introduces a hand profile setting to adjust the hand grip threshold, if needed. Some users were running into issues that their grip would release too soon due to tracking imprecision. This new setting allows to lower the required grip / curl threshold of the hand for it to be considered gripping.
- Fix: https://github.com/XRTK/XRTK-Core/issues/665
- Fix some inconsitencies with bold labels in profile inspectors
- Lowers default threshold
This is a breaking change and bumps Core up to 0.2.2.
- [SDK](https://github.com/XRTK/SDK/pull/222)
- [Lumin](https://github.com/XRTK/Lumin/pull/98)
- [Oculus](https://github.com/XRTK/Oculus/pull/104)
- [WMR](https://github.com/XRTK/WindowsMixedReality/pull/117)
- …
=> Implement grip threshold profile setting

XRTK-Core/Packages/com.xrtk.core/Editor/ControllerPopupWindow.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/BaseMixedRealityControllerDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/packages-lock.json
Fixed inspector to render the mapping profiles correctly if we're missing a left or right controller.
- Fixes rendering of the controller mapping profiles if we're missing a left or right controller
- Cleaned up old references for the `WindowsMixedRealityMotionController` mapping workaround for displaying HoloLens One input actions. We now have a dedicated `HoloLensOneController` type for HoloLens hand input on the HoloLens One (see [submodule changes](https://github.com/XRTK/WindowsMixedReality/pull/120))
- [WMR](https://github.com/XRTK/WindowsMixedReality/pull/120)
=> Updated Controller Mapping Data Provider Profile Inspector

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs
Delay showing the dialog for no profile when setting up to prevent dialog cancellation on mac
=> Delay showing the dialog until the next editor gui update

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs
- fixed some issues with AccessViolationException errors that can happen sometimes
=> Fix symbolic linker errors

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs
Fixes a few more edge cases when handling symlinks
=> handle a few more edge cases with symlinks

XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/TypeReferencePropertyDrawer.cs
Added try/catch around assembly load in `TypeReferencePropertyDrawer.GetFilteredTypes`
- Fixes: https://github.com/XRTK/XRTK-Core/issues/813
=> Fixed issue with platform dropdown when platform not installed.

XRTK-Core/.editorconfig, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/UnityObjectExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Lines/DataProviders/BezierLineDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/MathUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Tests/Services/ITestExtensionDataProvider1.cs
Added .editorconfig to help keep project in compliance with coding guidelines
=> Added .editorconfig to help keep project in compliance with coding guidelines

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Updated the Package installer to also populate Boundary system provider configuration
Added extra target for package installer
=> Update Package installer to install boundary config

XRTK-Core/Packages/com.xrtk.core/Editor/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AssemblyDefinitionEditorExtension.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AssemblyDefinitionPreProcessor.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AssemblyDefinitionPreProcessor.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Provides a way to list the version of the xrtk or one of the associated packages using the assembly version name.
Example:
```csharp
typeof(MixedRealityToolkit).Assembly.GetName().Version;
```
where the type is one of the types in the assembly you're wanting to get the version of.
```csharp
foreach (var (module, version) in MixedRealityToolkit.Modules)
{
Debug.Log($"{module}, v{version}");
}
```
- Fixes: #648
=> auto update assembly version based on package.json info

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityToolkitRootProfileInspector.cs
Ensure the root profile configurations are viewable at all times
=> always show root profile configurations

XRTK-Core/Packages/com.xrtk.core/Editor/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLink.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/StringExtensions.cs, XRTK-Core/Packages/com.xrtk.core/package.json
fixed some edge cases when generating symbolic links
=> fixed some edge cases when generating symbolic links

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/MixedRealityInputSystemProfileInspector.cs
The aggregated controller action mappings inspector in the input system profile inspector would only display hand controller mappings instead of all controller mappings. Fixed.
=> Fix controller action mappings only display hand controller mappings

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityInspectorUtility.cs
The inspector utility was using the wrong themed logo. This was not an issue with default XRTK inspectors since we use the same logo for both themes. But in custom extension service inspectors the issue was noticable.
=> Fix themed logo usage

XRTK-Core/Packages/com.xrtk.core/Runtime/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/BaseMixedRealityProfile.cs
Removed the `internal` keyword on the `BaseMixedRealityProfile.ParentProfile` property setter. This was necessary to be able to set parent profiles  in code that lives in another assembly.
=> Remove internal flag on parent profile property

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Fixed an exception when package installer tries to create a directory when a symbolic link is already pointing to it
=> Fixed package installer exception

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/LocomotionSystem/BlinkTeleportLocomotionProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/LocomotionSystem/BlinkTeleportLocomotionProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/LocomotionSystem/BlinkTeleportLocomotionProvider.cs
I need the blink teleport provider to support scriptable render pipelines. In the legacy pipeline it was possible to change a materials properties to support transparency at runtime. With render pipelines this is not possible anymore for performance reasons (they said). So I made the material used for blinking a configurable setting in the provider's profile, which is useful in many ways anyways. Also exposed two more settings that were hardwired in the provider previously.
- Exposed fade material and colors as settings in the blink teleport provider profile
- https://github.com/XRTK/com.xrtk.sdk/pull/246
=> Enable scriptable render pipeline support for Blink Teleport Provider

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
Fixes a small issue introduced with #898 where the `Camera Rig Component` was added to the Rig root transform AND the camera transform itself.
=> Fix camera rig component added to camera and rig transform

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/InputSystem/MixedRealityInputSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Updated requirements check behavior. The toolkit will add an `EventSystem` / `StandaloneInputModule` only if needed. If the developer has a custom setup it will leave it alone. The toolkit will raise errors if multiple instances of either exist.
=> Make use of existing event system setup if available

XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/DiagnosticsSystem/IMixedRealityFrameDiagnosticsDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/DiagnosticsSystem/IMixedRealityFrameDiagnosticsDataProvider.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/DiagnosticsSystem/MixedRealityFrameDiagnosticsDataProvider.cs
Introduced `IMixedRealityFrameDiagnosticsDataProvider` and exposed frame diagnostics so they can be read by third party implementations for custom logging etc. without relying on the diagnostics window.
=> Exposed frame diagnostics for third party consumption

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/BaseMixedRealityCameraDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/CameraSystem/BaseMixedRealityCameraDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/CameraSystem/IMixedRealityCameraDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/CameraSystem/DefaultCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/CameraSystem/TrackingType.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/CameraSystem/TrackingType.cs.meta
Implements a new `TrackingType` setting for camera data providers. It allows whether the camera rig should operate in 3DOF or 6DOF mode.
Scenario: A device supports 6DOF tracking but the developer wants it to not make use of it and use 3DOF instead.
=> Implement tracking type configuration for camera data providers

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/BaseMixedRealityCameraDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/CameraSystem/BaseMixedRealityCameraDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
Added ` eyeTextureResolution` setting to `BaseCameraDataProvider` profile and implementation to apply to the `XRSettings.eyeTextureResolutionScale` Unity setting. This is useful when targeting multiple platforms and the camera needs scale differently. In my use case
- Meta Quest -> texture scale 2
- Pico -> texture scale 1
=> Implement eyeTextureResolution setting for camera data providers

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
Removed the hard-coded default head height value `1.6`. The initial idea here was back then to have a reasonable default head height in case the profile value is `0`. As it turns out this was a mistake, some people WANT explicitly to have 0 as the default head height, e.g. when using Tracking Origin Mode `Device`, which was recently introduced as a setting to the camera system.
=> Remove hard coded default head heigth value

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/CameraSystem/DefaultCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/LocomotionSystem/LocomotionSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/CameraCache.cs
Updated the camera validation and regeneration as a result of #911 
* Moved Camera validation routines to "OnEnable" in the Camera Provider
* Moved Rig Validation to the OnValidate method, so it is checked at the right time
* Added Rig Validation to the Toolkit Validation methods
* Ensured Toolkit validation ONLY occurs when a profile has been assigned
* Fixed a random bug whereby CameraCache was being called in OnDestroy without first checking there was a camera to destroy (as it created a new camera)
* Updated validation warnings
Tested all scenarios where the scene will be validated:
* New Scene
* New Scene + Configure
* New GO + Toolkit object
* Deleting Toolkit and readding
* Deleting Rig and checking configuration
Fixes: 
- https://github.com/XRTK/com.xrtk.core/issues/911
None
=> Updated Camera validation
