CODING_GUIDELINES.md, CONTRIBUTORS.ms, README.md
Getting started on updating the front page docs
=> Updating readme and front page docs

XRTK-Core/ProjectSettings/ProjectVersion.txt
=> updated project version

XRTK-Core/Assets/XRTK.SDK/DefaultProfiles/Input/DefaultControllerMappings/DefaultWindowsMixedRealityControllerMappingProfile.asset
**Overview**
Fixed the namespace issue in the default WMR controller mapping asset
**Changes:**
- Fixes: Controllers working
**Breaking Changes:**
- Breaks nothing
=> Fixed the namespace issue in the default WMR controller mapping asset

XRTK-Core/Assets/XRTK/Definitions/Utilities/MixedRealityPose.cs, XRTK-Core/Assets/XRTK/Services/InputSystem/FocusProvider.cs, XRTK-Core/Assets/XRTK/Services/InputSystem/MixedRealityInputSystem.cs
- Additional MixedRealityPose information
- Focus Provider formatting
- Input System Bugfix
=> Development Ports

XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
- updated player build tools to include the option to specify a csv scene list string or file.
- misc cleanup
=> Ported command line scene list

XRTK-Core/Assets/XRTK.SDK/DefaultProfiles/DefaultMixedRealityToolkitConfigurationProfile.asset, XRTK-Core/Assets/XRTK/Definitions/Utilities/SystemType.cs, XRTK-Core/Assets/XRTK/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs, XRTK-Core/Assets/XRTK/Inspectors/SystemTypeRepairWindow.cs, XRTK-Core/Assets/XRTK/Inspectors/SystemTypeRepairWindow.cs.meta
- ported system type search when missing type is detected and added better inspector error icons
=> SystemType reference fixing port

XRTK-Core/Assets/XRTK/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/MixedRealityControllerDataProvidersProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/MixedRealityControllerMappingProfiles.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/MixedRealityControllerVisualizationProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/OpenVR/GenericOpenVRControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/OpenVR/OculusRemoteControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/OpenVR/OculusTouchControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/OpenVR/ViveWandControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/UnityInput/GenericUnityControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/UnityInput/MouseControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/UnityInput/TouchScreenControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/UnityInput/XboxControllerMappingProfile.cs, XRTK-Core/Assets/XRTK/Definitions/DiagnosticsSystem/MixedRealityDiagnosticsProfile.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealityGesturesProfile.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealityInputActionRulesProfile.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealityInputActionsProfile.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealityPointerProfile.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealitySpeechCommandsProfile.cs, XRTK-Core/Assets/XRTK/Definitions/MixedRealityCameraProfile.cs, XRTK-Core/Assets/XRTK/Definitions/MixedRealityRegisteredServiceProvidersProfile.cs, XRTK-Core/Assets/XRTK/Definitions/NetworkingSystem/BaseMixedRealityNetworkProviderProfile.cs, XRTK-Core/Assets/XRTK/Definitions/NetworkingSystem/MixedRealityNetworkSystemProfile.cs, XRTK-Core/Assets/XRTK/Definitions/NetworkingSystem/MixedRealityWebRtcNetworkProviderProfile.cs, XRTK-Core/Assets/XRTK/Definitions/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystemProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Utilities/ProfileMenuItemIndices.cs
updated assets context menu order for all xrtk scriptable object asset creation menus
=> Updated asset creation menus for profiles and scriptable objects

XRTK-Core/Assets/XRTK/Definitions/Controllers/BaseMixedRealityControllerDataProviderProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Controllers/BaseMixedRealityControllerDataProviderProfile.cs.meta, XRTK-Core/Assets/XRTK/Definitions/InputSystem/ControllerDataProviderConfiguration.cs, XRTK-Core/Assets/XRTK/Definitions/InputSystem/MixedRealityGesturesProfile.cs, XRTK-Core/Assets/XRTK/Inspectors/Profiles/MixedRealityControllerDataProviderProfileInspector.cs, XRTK-Core/Assets/XRTK/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/BaseDictationDataProvider.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/BaseSpeechDataProvider.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/OpenVR/OpenVRDataProvider.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/UnityInput/MouseDataProvider.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/UnityInput/UnityJoystickDataProvider.cs, XRTK-Core/Assets/XRTK/Providers/Controllers/UnityInput/UnityTouchDataProvider.cs, XRTK-Core/Assets/XRTK/Services/MixedRealityToolkit.cs
Moved the windows platform specific gestures from the gesture profile to the platform's controller data provider profile.
- Fixes: #75
- Windows platform specific gesture settings are now located in the windows mixed reality controller data provider profile.
=> Gestures update

XRTK-Core/Assets/XRTK/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs, XRTK-Core/Assets/XRTK/Utilities/Async/Awaiters.cs
- added a longer timeout for listing packages.
- fixed a docfx error
- updated modules
=> misc error corrections

XRTK-Core/Assets/XRTK/Services/MixedRealityToolkit.cs
- removed an exception that could be thrown when creating a service instance
- now destroys the whole GameObject that the component is attached to when multiple instances are found.
=> Cleaned up the MixedRealityToolkit class a bit

XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/BuildInfo.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/IBuildInfo.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
uses EditorBuildSettingsScenes instead of strings
=> Build Tools Update

XRTK-Core/Assets/XRTK/Definitions/MixedRealityRegisteredServiceProvidersProfile.cs, XRTK-Core/Assets/XRTK/Definitions/Utilities/SystemType.cs, XRTK-Core/Assets/XRTK/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs, XRTK-Core/Assets/XRTK/Services/MixedRealityToolkit.cs
- Fixes #41
- services are now prioritized by the order of the list
- list can be dragged for easy reordering
=> Updated the extension service profile

XRTK-Core/Assets/XRTK/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/BuildInfo.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs, XRTK-Core/Assets/XRTK/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
Updated the build player to show a list of scenes for the build
=> Fixed symbolic linking in CI

XRTK-Core/Assets/XRTK/Providers/Controllers/BaseController.cs
- applies the wmr fixes in https://github.com/XRTK/WindowsMixedReality/pull/12
=> WMR Controller Updates

XRTK-Core/Assets/XRTK/Definitions/MixedRealityCameraProfile.cs, XRTK-Core/Assets/XRTK/Definitions/MixedRealityToolkitConfigurationProfile.cs, XRTK-Core/Assets/XRTK/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Assets/XRTK/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs, XRTK-Core/Assets/XRTK/Inspectors/Utilities/Packages/MixedRealityPackageSettings.asset, XRTK-Core/Assets/XRTK/Interfaces/CameraSystem.meta, XRTK-Core/Assets/XRTK/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs, XRTK-Core/Assets/XRTK/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs.meta, XRTK-Core/Assets/XRTK/Services/CameraSystem.meta, XRTK-Core/Assets/XRTK/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Assets/XRTK/Services/CameraSystem/MixedRealityCameraSystem.cs.meta, XRTK-Core/Assets/XRTK/Services/MixedRealityToolkit.cs, XRTK-Core/Assets/XRTK/package.json
- Added the Mixed Reality Camera System and moved some `IsOpaque` from the camera profile to the service itself.
- Bumped version to 0.1.3
=> Added Camera System

XRTK-Core/Assets/XRTK/Attributes/SystemTypeAttribute.cs, XRTK-Core/Assets/XRTK/Definitions/SpatialObservers/BaseMixedRealitySpatialMeshObserverProfile.cs, XRTK-Core/Assets/XRTK/Inspectors/Profiles/SpatialAwareness/BaseMixedRealitySpatialMeshObserverProfileInspector.cs, XRTK-Core/Assets/XRTK/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs
- Adds the ability to assign additional components to be added to the generated mesh
- Adds the ability to assign a prefab in place of the generated mesh
=> ported spatial understanding improvements from private fork.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/request_for_information.md, .github/PULL_REQUEST_TEMPLATE.md
Updated templates to be clearer.
Included an RFI template to let anyone simply ask a question (all answers aid documentation / training)
=> Update GitHub templates

XRTK-Core/Assets/XRTK/Definitions/Devices/ControllerMappingLibrary.cs
- Fixed a bug with the controller mapping library when a profile is null when attempting to get the texture
=> Fixed bug in Controller Mapping Library when getting controller texture

XRTK-Core/Assets/XRTK/Extensions/VectorExtensions.cs
- added offset to `RadialMapping` Vector extension to get proper alignment of objects
=> Radial Mapping Vector Extension offset 

XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_01_MixedRealityToolkitTests.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/ControllerPopupWindow.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs, XRTK-Core/Packages/com.xrtk.core/package.json
- Fixed controller popup window
=> fixed finding absolute path for com.xrtk.core

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
- Also updated the warning message for missing link settings.
=> Set package settings immediately if created

XRTK-Core/Assets/XRTK.Tests/InputSystem/TestFixture_02_InteractionDefinitionTests.cs
Just syncs up the submodule checkouts with the latest development branch checkouts for each.
=> Dev modules update

XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/ProjectSettings/ProjectVersion.txt
Editor version 2019.1.1f1 and xrtk.core version 0.1.10
=> bumped editor version and package version

XRTK-Core/Packages/com.xrtk.core/Definitions/SpatialAwarenessSystem/SpatialMeshDisplayOptions.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialMeshObserver.cs, XRTK-Core/Packages/com.xrtk.core/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs
Added the ability to set the mesh display option at runtime and added an additional option of colliders only.
TODO:
=> Spatial Awareness display options enhancement

XRTK-Core/Packages/com.xrtk.core/Extensions/CanvasExtensions.cs
Removed an always expression and replaced it with true.
=> removed always true expression

XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs
Ported change from mrtk that updates solvers to use lifetime.
=> ported an update to solvers to use the current lifetime

XRTK-Core/Packages/com.xrtk.core/Definitions/BoundarySystem/InscribedRectangle.cs, XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
ported fix to possible infinite loop/stack overflow for boundary system.
=> Ported inscribed rect fixes

XRTK-Core/Packages/com.xrtk.core/Utilities/Async/Awaiters.cs
Added cancellation if playstate changes while awaiting indefinite changes
=> Cancellation for indefinite awaiters when changing play mode state

XRTK-Core/Packages/com.xrtk.core/README.md.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployPreferences.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployWindow.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildInfo.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildInfoExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/IBuildInfo.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/MixedRealityAppIcon.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpBuildInfo.cs.meta, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs.meta
=> Dev meta fixes

XRTK-Core/ProjectSettings/ProjectSettings.asset, XRTK-Core/ProjectSettings/ProjectVersion.txt
[Updates the editor to 2019.1.8f1](https://unity3d.com/unity/whats-new/2019.1.8)
- Extension
- Component ported from another framework
=> updated editor to 2019.1.8f1

XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployWindow.cs, XRTK-Core/ProjectSettings/ProjectSettings.asset
High level overview of this pull request.
- Extension
=> Ported some build window perf fixes

XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityService.cs
Minor fix for a property comment.
- Fix code documentaton for name property
=> Fix documentation for display name

XRTK-Core/Packages/com.xrtk.core/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/package.json
Missing updates required in Core for Oculus module
=> Missing updates required in Core for Oculus module

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
Updates the Symbolic link verification so we're not using Powershell. Seems that some machines cannot run it and this is more cross platform for editors like Linux and Mac
- updated symbolic link verification process that some people found.
- This also fixes the infinite recursion some people were getting as well.
=> updated symbolic link verification

XRTK-Core/Packages/com.xrtk.core/Definitions/InputSystem/MixedRealityInputAction.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Physics/RayStep.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/MixedRealityRaycaster.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
- Fixed a bug in `RayStep` where direction wasn't properly being calculated.
- Updated equality check for input action to use pattern matching of the type
- Misc documentation
=> Misc cleanup and RayStep direction bug fix

XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs
Fixed the bug with package settings asset not being saved to disk after making a change
- Fixes: https://github.com/XRTK/XRTK-Core/issues/186
=> Fixed package settings serialization bug

XRTK-Core/Packages/com.xrtk.core/package.json
=> bumped version to 0.1.14

README.md
Update XRTK Readme to include Oculus
=> Update XRTK Readme to include Oculus

README.md
=> Update readme to include Discord link

XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs
Fixed the missing oculus sdk package download.
=> Added generated oculus package info if missing

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/AssemblyDefinitionEditorExtension.cs
Additional fixes for the 2019.2 editor runtime
=> Additional fixes for the 2019.2 editor runtime

XRTK-Core/Packages/com.xrtk.core/Definitions/Physics/FocusDetails.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystemProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/SpatialObservers/BaseMixedRealitySpatialMeshObserverProfile.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwareness/BaseMixedRealitySpatialMeshObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwareness/MixedRealitySpatialAwarenessSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IMixedRealityPointer.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IPointerResult.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/FocusProvider.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/GenericPointer.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/MixedRealityInputSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/TeleportSystem/MixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/package.json
=> Release 0.1.17

XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
Added application details to diagnostics window
- Fixes: https://github.com/XRTK/XRTK-Core/issues/229
=> added application name and version to diagnostics window

XRTK-Core/Packages/com.xrtk.core/package.json
Update release to 0.1.18 for next update
=> Update release to 0.1.18 for next update

.github/FUNDING.yml
Users were concerned with the error on the Sponsor link.  Commenting out GitHub sponsors users until we get accepted.
=> Users were concerned with the error on the Sponsor link.

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackagesWindow.cs
added a missing private access modifier
=> fixed missing access modifier

.gitmodules
- Removed upm extension submodule
- Updated submodule checkouts
=> removed upm extension submodule

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/CanvasEditorExtension.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/CanvasUtility.cs
Fixed the canvas utility issues described in #159
- Fixes: #159
=> Fixed canvas utility removing itself

XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
Pulls the core and sdk by default
- Addresses #325
=> pull the sdk and core by default

XRTK-Core/Packages/com.xrtk.core/Extensions/BoundsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/LayerExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/TextureExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/UnityObjectExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityStandardShaderGUI.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/GitUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/MixedRealityControllerMapping.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/MixedRealityAppIcon.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/ConstructGltf.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/GltfUtility.cs
=> removed unsused declarations and a bit of formatting

XRTK-Core/Packages/com.xrtk.core/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Added a delay call to all object pings for the toolkit or it's profiles.
Reworked the configuration methods to ensure we're properly saving the scene.
- Core
- Fixes: #174
=> Added a delay call to all object pings and reworked configure method

XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Checks to make sure the service isn't set to none and then checks if the platform is supported
=> Make sure we're not set to none

XRTK-Core/Packages/com.xrtk.core/Inspectors/XRTK.Inspectors.asmdef
=> removed unused ugui reference

XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Better support for editor platform checking
- Fixes: #354
=> Fixed editor platform support checking

XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/PathFinder.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/PathFinder.cs.meta
Added a less laggy way to find the package path.
=> Improved package path lookup

XRTK-Core/Packages/com.xrtk.core/Inspectors/XRTK.Inspectors.asmdef, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/XRTK.Utilities.Build.asmdef, XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/Importers/XRTK.Utilities.Gltf.Importers.asmdef, XRTK-Core/Packages/com.xrtk.core/XRTK.asmdef
updated assembly references to use guids
=> updated assembly references to use guids

XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/FocusProvider.cs
Update to improve focus initialization and pre-updates for the InputAction Refactor
* Adds initialize capabilities to focus to address pointer issues
* Formatting on Camera system
* Adds a new extension to the Interaction Mappings to simplify input events
=> Update to improve focus initialization and pre-updates for the InputAction Refactor

XRTK-Core/Packages/com.xrtk.core/Attributes/Il2CppSetOptionAttribute.cs, XRTK-Core/Packages/com.xrtk.core/Attributes/Il2CppSetOptionAttribute.cs.meta
Added the `Il2CppSetOptionsAttribute` to help optimize specific calls during the build process.
More information about this can be found in the [Unity Manual: Compiler Options](https://docs.unity3d.com/Manual/IL2CPP-CompilerOptions.html)
=> Added unity's il2cpp attribute

XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Speech/WindowsSpeechDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseDataProvider.cs
=> Missed a few changes when pulling out controller data provider refactor

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Fixed the clone and customized button not functioning properly.
- Fixes: #370
=> Make sure we ping the cloned profile

XRTK-Core/Packages/com.xrtk.core/package.json
=> Update UPM version to 0.1.22

XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/BaseMixedRealityControllerMappingProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Hands/HandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Hands/UnityEditorHandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerMappingProfiles.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerVisualizationProfile.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/UnityEditor/UnityEditorHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/UnityEditor/UnityEditorHandPose.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/UnityEditor/UnityEditorHandPoseData.cs
Just a quick review of the hand simulation feature branch so far.
Cleaned up some errors and initialization problems.
=> Some quick review and change requests for feature/hand-simulation

XRTK-Core/Packages/com.xrtk.core/EventDatum/Input/MixedRealityPointerDragEventData.cs, XRTK-Core/Packages/com.xrtk.core/EventDatum/Input/MixedRealityPointerDragEventData.cs.meta, XRTK-Core/Packages/com.xrtk.core/EventDatum/Input/MixedRealityPointerEventData.cs, XRTK-Core/Packages/com.xrtk.core/EventDatum/Input/MixedRealityPointerScrollEventData.cs, XRTK-Core/Packages/com.xrtk.core/EventDatum/Input/MixedRealityPointerScrollEventData.cs.meta, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityPointerDragHandler.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityPointerDragHandler.cs.meta, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityPointerScrollHandler.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityPointerScrollHandler.cs.meta, XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IMixedRealityInputSystem.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchController.cs, XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/MixedRealityInputSystem.cs, XRTK-Core/Packages/com.xrtk.core/package.json
Changes: 
- Added a way to subscribe to input events from a poco class (#380)
- Dev/pointer dragging events (#382)
=> Release 0.1.23

.github/FUNDING.yml
=> Funding update2

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Updated the handedness recall and update in the inspector to be more efficient (removed Switch statement)
=> Updated Handedness use in the Visualization inspector

XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Update CameraSystem test validation in line with other systems to check:
* IsInitialized
* IsApplicationQuitting
* ActiveProfile ! null
* IsCameraSystemEnabled
=> Update Camera System static accessor validation logic

.github/FUNDING.yml, XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityCameraProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/TrackedObjectType.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityCameraRig.cs.meta, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/DefaultCameraRig.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/DefaultCameraRig.cs.meta, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs, XRTK-Core/Packages/com.xrtk.core/Services/TeleportSystem/MixedRealityTeleportSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/Orbital.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs, XRTK-Core/Packages/com.xrtk.core/XRTK.asmdef, XRTK-Core/ProjectSettings/ProjectSettings.asset
=> Release 0.1.24

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/package.json
We forgotten to remove an old property in the camera system inspector and need to push out a hotfix.
- Fixes: NRE in camera system profile
=> Fix/camera system inspector hotfix 

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/package.json
* fixed NRE in camera profile (#402)
* bumped version for hotfix
=> Release 0.1.25 hotfix

XRTK-Core/Packages/com.xrtk.core/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs, XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/Solver.cs
The body transform was pretty close, but there was some more tweaking to be done properly.
Made sure we're always moving the body position to the feet, and ensure we're syncing the position in camera local space.
- Fixes: #408
=> More rig sync updates

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
replaced assert with null check and return.
=> Replaced assert with return if null

XRTK-Core/Packages/com.xrtk.core/Services/BaseService.cs
Added some docs and removed some trailing spaces.
=> cleaned up base service

XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
attempted to fix possible crashes when updating the symbolic links settings asset
- Fixes: Crashing when editor attempts to update the symbolic link settings asset
=> [Fix] Symbolic Link crashes when updating asset

XRTK-Core/Packages/com.xrtk.core/Extensions/TransformExtensions.cs
Added ability to pass in cached references to avoid costly lookup
=> Vector Extensions optimizations

XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
Fixed some formatting and stuff in `Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs`
=> fixed some formatting

XRTK-Core/Packages/com.xrtk.core/Extensions/ArrayExtensions.cs
XRTK - Mixed Reality Toolkit Change Request
New array extension to allow easy addition of information to an existing array, as requested as part of #452
=> New array extension to allow easy addition of information to an existing array

XRTK-Core/Packages/com.xrtk.core/Extensions/ArrayExtensions.cs
Array extension, Added an additional parameter to specify Array Index
=> Array extension, Added additional parameter to specify Array Index

XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs, XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs.meta, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerDataProvidersProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerMappingProfiles.cs, XRTK-Core/Packages/com.xrtk.core/Extensions/ArrayExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
Extension of the Controller Mapping validations, as data providers also need validating that they exist when you add a new platform.
=> Controller Mapping / Provider validations part 2

XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
Change Requests and bug fixes from Validation Changes #452 
- Fixes: [Object lifetime bypassing](https://github.com/JetBrains/resharper-unity/wiki/ScriptableObjects-must-be-instantiated-with-ScriptableObject.CreateInstance-instead-of-new)
=> Change Requests from Validation Changes

XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/SceneHelpers.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/SceneHelpers.cs.meta
Transferring new SceneHelper script to core
=> Transferring new SceneHelper script to core

README.md, articles/A02-ChoosingXRTKvsMRTK.md
Updated the home page and comparison articles lists of supported platforms based on feedback
=> Documentation update

XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_03_ExtensionsTests.cs
There was some static analysis errors from resharper I wanted to remove from the tests.
=> Removed some resharper errors in the tests

XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs
Fixed the parent profile property not correctly being set
Fixed the type reference property drawer try repair buttons to render correctly
- Fixes: #477 
- Fixes: #475
=> Fixed some issues with the MixedRealityServiceProfileInspector

XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Simulation/Hands/SimulatedHandControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs
This should get the branch to compile successfully again.
All I did was add the required fields to the profile.
=> updated simulated hand data profile with required fields for IMixedRealityHandControllerDataProvider

.gitignore, XRTK-Core/ProjectSettings/ProjectSettings.asset
- added ios project settings
- ignored app.meta
=> Updated project settings

README.md
=> Added OpenUpm Badges to readme

XRTK-Core/Packages/com.xrtk.core/Definitions/RuntimePlatformEntry.cs.meta
Updated oculus sdk to latest checkout
=> fixed missing icons

XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs
- Adds `gameObject.GetOrAddComponet<Component>()`
=> ported game object extension from #216

XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Hands/HandData.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Hands/RecordedHandJoint.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Simulation/Hands/SimulatedHandControllerPose.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/AndroidPlatform.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/IMixedRealityController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/MixedRealityHandController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/GenericOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusRemoteOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveKnucklesOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveWandOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/BaseSimulatedControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityJoystickDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/XboxController.cs
- Added IMixedRealityControllerDataProvider to IMixedRealityController
- updated all the controller constructors to take a data provider parameter
- got Lumin hand controllers working
=> change-request/hand-tracking

XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/BaseMixedRealityControllerDataProviderProfile.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerVisualizationProfile.cs, XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/IMixedRealityController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/MixedRealityControllerMapping.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/GenericOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusRemoteOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveKnucklesOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveWandOpenVRController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/MouseDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityJoystickDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchController.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/UnityTouchDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/XboxController.cs
Broke out the controller changes form the hand tracking PR
- Updated the constructors on all controllers to include the `IMixedRealityControllerDataProvideder` as a parameter.
- Added `IMixedRealityController.ControllerDataProvider`
- Added `IMixedRealityController.AngularVelocity`
- Added `IMixedRealityController.Velocity`
=> added controller data provider reference to the controller

XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/OSXPlatform.cs, XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/WindowsStandalonePlatform.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitRootProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Pulled out some changes from #517 
- Fixed platforms so they only return true outside of the editor
- Fixed a race condition after we've reset the profile and started re-initialization
https://github.com/XRTK/Lumin/pull/61
=> Updated Platforms

XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityServiceProfile.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
updated the oculus and sdk submodule checkouts and fixed any broken platform reference
https://github.com/XRTK/SDK/pull/158
=> updated oculus checkout and fixed platform definitions for all configurations

XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/CurrentBuildTargetPlatform.cs, XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Moved the editor check out to the service locator.
=> updated check for current build target

XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityToolkitRootProfile.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/EditorGUILayoutExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/SerializedPropertyExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/SerializedPropertyExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityCameraDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/DiagnosticsSystem/MixedRealityDiagnosticsSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitRootProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySpatialMeshObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySpatialObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySurfaceObserverProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProviderInspector.cs, XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Lines/DataProviders/SplineDataProviderInspector.cs
- updated all properties to use if possible
- updated sdk inspectors as well
=> Added serialized property extension for bold foldout

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/MixedRealityInputSystemProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/ArrayExtensions.cs, azure-pipelines.yml
fixed an NRE when trying to render a mapping profile
fixed a typo
=> Fixed NRE in input system profile inspector 

XRTK-Core/Packages/com.xrtk.core/LICENSE.md
updated license, readme, and changelogs in all repos
=> Housekeeping tasks

XRTK-Core/Packages/com.xrtk.core/Editor/ControllerPopupWindow.cs
- Fixes #553 
- https://github.com/XRTK/SDK/pull/169
=> Fixed the nre with the controller mapping winow

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs.meta
1st pass clean up pr, resolving QA issues for 0.2 release
=> Icon fixes - cleanup - 0.2 QA

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/UnityFileHelper.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/UnityFileHelper.cs.meta
Updated package installer to accept multiple sources and destinations
Updated sdk package installer to match the pattern in the other package installers. 
https://github.com/XRTK/SDK/pull/176
=> Change request/package installer

XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
Don't add the registry if it already exists
=> Don't add the registry if it already exists

azure-pipelines.yml, azure_pipelines/common.yml, azure_pipelines/stages/publish.yml, azure_pipelines/stages/steps/build-docfx.yml, azure_pipelines/stages/steps/build-docs.yml, azure_pipelines/stages/steps/export-package-seed.yml, azure_pipelines/stages/steps/run-unity-tests.yml, azure_pipelines/stages/steps/upm-package-info.yml, azure_pipelines/stages/unity-build.yml
Adds the ability to publish preview packages for `master <- development` pull requests
=> added upm preview package publishing capabilities

XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Shaders/MixedRealityStandard.shader
Fixed the reference to the gui editor in the standard shader
=> fixed standard editor shader reference

XRTK-Core/Assets/XRTK.Seed/PackagePickerWindow.cs, XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Editor/MixedRealityEditorSettings.cs
Added the ability to install preview packages from the seed installer.
- Added preview install capability
- Fixed pref key
- updated lumin checkout
- [SDK](https://github.com/XRTK/SDK/pull/185)
- [Lumin](https://github.com/XRTK/Lumin/pull/78)
=> Updated package seed installer

XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
Fixed the new package seed from adding the xrtk scoped registry more than once
=> Fixed package seed so it doesn't add registry more than once

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Platforms/CurrentBuildTargetPlatform.cs
always return true if editor platform is defined
=> Fixed Editor Only services

XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/AxisConstraintAttributeDrawer.cs.meta, XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MixedRealityInputActionDropdown.cs.meta
Fixed some errors with meta in 2019.3
=> fixed some errors with meta files in 2019

.gitignore, .gitmodules, XRTK-Core/Assets/XRTK.Generated/SymbolicLinkSettings.asset
This one slipped past us https://github.com/XRTK/SteamVR
=> added steam vr submodule

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs
Updated SteamVR checkout
Made the Guid Regenerator public for general availability 
- [SteamVR](https://github.com/XRTK/SteamVR/pull/3)
=> Make Guid Regenerator public

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/MixedRealityInteractionMappingProfileInspector.cs
Fixed axis processor inspectors from being unresponsive
- https://github.com/XRTK/SDK/pull/188 Readded teleport pointer references and fixed wmr input actions
- https://github.com/XRTK/WindowsMixedReality/pull/84
=> Axis processor serialization fix

XRTK-Core/Assets/XRTK.Generated/_TestProfiles/TestMixedRealityToolkitRootProfile/MixedRealityInputSystemProfile.asset, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/UnityInput/MouseController.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/UnityInput/MouseDataProvider.cs
Fixed mouse input
Fixes #38 
- https://github.com/XRTK/SDK/pull/187
=> updated mouse input

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/UnityInput/MouseDataProvider.cs
Adds better mouse context switching when using hand simulation, and when switching input from game window to editor, etc.
- https://github.com/XRTK/SDK/pull/189
Blocked by Submodule changes
=> better mouse context switching

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/RecordedHandJoint.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/RecordedHandJoints.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Hands/TrackedHandJoint.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Controllers/Simulation/Hands/SimulatedHandControllerPose.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/HandControllerPoseDefinitionExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/MixedRealityHandController.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Simulation/Hands/SimulatedHandDataConverter.cs
Mainly wanted to cleanup the serialization of the recorded joints, and replace the reference types with value types in the data structures. I reserialized all the json structures, and saved them back.
I also fixed the build errors
https://github.com/XRTK/SDK/pull/192
=> Hand input and poses change request

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/InteractionMode.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/InteractionMode.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/EnumExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/EnumExtensions.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/InputSystem/IMixedRealityPointer.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/InputSystem/GazeProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/InputSystem/GenericPointer.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/XRTK.asmdef, XRTK-Core/Packages/com.xrtk.core/Tests/Extensions.meta, XRTK-Core/Packages/com.xrtk.core/Tests/Extensions/EnumExtensionTests.cs, XRTK-Core/Packages/com.xrtk.core/Tests/Extensions/EnumExtensionTests.cs.meta
Added enum extensions and tests
Added `InteractionMode` to pointers to better help distinguish their capabilities.
Added `EnumExtensions` and tests to make it easier to set, toggle, and evaluate bit flags.
https://github.com/XRTK/SDK/pull/194
=> Added interaction mode to pointers

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs
Fixes #614 UnauthorizedAccessException when installing packages
=> Fixed UnauthorizedAccessException when installing packages

XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/DataProvider.txt, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityServiceWizard.cs
- Fixed some issues generating certain generic types when using the serice wizard.
- No longer generates profile class if one isn't required.
=> Fixed some service generation issues with with service wizard

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Fixed some warnings and errors when entering/exiting playmode in editor
=> Fixed some warnings and errors when starting/stopping playmode in editor

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/ProcessExtensions.cs
Fixes bugs when trying to run commands for other processes other than the terminal.
=> Don't add command arg if we're not actually processing a terminal command

XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs, azure_pipelines/common.yml, azure_pipelines/stages/steps/install-unity.yml, azure_pipelines/stages/unity-build.yml
=> Fix android CI/CD builds

azure_pipelines/stages/steps/build-unity-player.yml, azure_pipelines/stages/steps/export-package-seed.yml, azure_pipelines/stages/steps/install-unity.yml, azure_pipelines/stages/steps/return-unity-license.yml, azure_pipelines/stages/steps/run-unity-tests.yml, azure_pipelines/stages/unity-build.yml
- Extended job timeout to 2 hours
- Fixed the wait for the creation of the log
=> CI/CD Fixes

XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
Fixed the NRE thrown when changing camera data provider values.
- Fixes: #653
=> Fix NRE thrown by changing predicate order

.github/FUNDING.yml
Modestly added myself to the GitHub sponsors list.
Added `FejZa` to GitHub sponsors nickname array
=> Add FejZa to GitHub sponsors listing

azure_pipelines/stages/steps/install-unity.yml
Fixes the [module installation bug ](https://forum.unity.com/threads/hub-cli-missing-modules.974301/)
=> Temp fix Hub module installation bug

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityPreferences.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLink.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs
Updated the symbolic linker utility to be more useful to other projects that may want to use it.
- Fixed symbolic link validation. Previously stale symlinks were not being deleted correctly
- Made `SymbolicLinker` public to make it easier to Sync symbolic links in external projects using the utility
- Made `SymbolicLinks.IsActive` setter public to make it easier to toggle symbolic links on and off
=> Updated symbolic link Utilities

XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/Hands/BaseMixedRealityHandControllerDataProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/Simulation/SimulatedHandControllerDataProviderProfileInspector.cs
Fixed the inspector for SimulatedHandControllerDataProviderProfileInspector to be able to properly assign the Tracked Hand Poses
- Fixes: https://github.com/XRTK/XRTK-Core/issues/691
=> Fixed simulated hand data provider Tracked Hand Pose list rendering

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/UnityFileHelper.cs
- Fixes: #689 
- Fixes: https://github.com/XRTK/SDK/issues/201
=> Added json files to the list of UnityFileExtensions

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Addresses https://github.com/XRTK/Oculus/issues/92
=> Fix NRE on package asset import

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
This is a hotfix for yesterday's PR. Sorry I messed it up. The condition for the installer was wrong and instead of fixing the NRE it opened the door wide open for it.
=> Fix condition for package installer

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Added  error for edge case when an `activeProfile` isn't assigned to the service locator
=> added error message when we cannot enter play mode

XRTK-Core/Packages/packages-lock.json, XRTK-Core/ProjectSettings/ProjectVersion.txt
=> updated project to 2019.4.16

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/MixedRealityServiceConfiguration.cs
Fixed issue where configuration would lose the runtime platform types when installed.
- Fixes: #739
=> Fixed issue where configuration would lose the runtime platform types when installed

articles/toc.yml, docfx_project/docfx.json, docs/README.html, docs/articles/toc.html, docs/manifest.json
updated landing page to that table of contents is on the landing page.
=> updated landing page

XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/SpatialObservers/BaseMixedRealitySpatialMeshObserverProfile.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialMeshObserver.cs, azure-pipelines.yml
- fixed missing member in documentation
- updated azure pipelines excluded folder paths
=> fixed missing member in documentation

XRTK-Core/Packages/com.xrtk.core/package.json
Bumps the core version up to 0.2.1 due to recent breaking changes.
=> Bump Core version

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs
updated assertion check when configuring the start scene
- Fixes: #759
=> updated assertion check when configuring the start scene

XRTK-Core/Packages/com.xrtk.core/Editor/EditorActiveProfileChangeHandler.cs, XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/RenderPipeline.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/RenderPipeline.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/RenderPipelineUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/RenderPipelineUtilities.cs.meta, XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/packages-lock.json
Hotfix release to fix auto-initialization
=> Release 0.2.2

XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UnityPlayerBuildTools.cs
Better project validation for CI/CD tools
=> Added a ValidateProject method to build tools

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityPreferences.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AutoSceneSwitcher.cs, XRTK-Core/Packages/manifest.json, XRTK-Core/Packages/packages-lock.json
fixes #758 when trying to start a scene without the xrtk initialized in the project
=> Fixed XRTK auto-initialization for auto scene switcher

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityPreferences.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AutoSceneSwitcher.cs, XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/manifest.json, XRTK-Core/Packages/packages-lock.json
Hotfix to address auto-initialization
=> Release 0.2.4 Hotfix

.gitignore, azure-pipelines.yml
- added resharper cache to gitignore
- removed webxr build temporarily until the feature is complete
=> Removed WebXR Build from CI/CD temporarily

XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UnityPlayerBuildTools.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UwpPlayerBuildTools.cs
- Test to see if it is possible to set the il2cpp cache directory
- Cleaned up command line build to get the utilize the build report
=> Tweaked CI/CD builds

XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/packages-lock.json, XRTK-Core/ProjectSettings/ProjectSettings.asset, XRTK-Core/ProjectSettings/ProjectVersion.txt
updated project to Unity 2019.4.19f1
=> updated project to Unity 2019.4.19f1

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/StringExtensions.cs, XRTK-Core/Packages/com.xrtk.core/package.json
- Fixed package installer failing to copy assets on Linux and MacOs
- updated string extensions bc it was super confusing and poorly written
- Fixes: #783
=> Fixed packages installer

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, azure-pipelines.yml
updated branch references from master to main
- https://github.com/XRTK/AzurePipelines/pull/7
=> updated branch references from master to main

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs
Fixed editor hanging when symbolic link path is no longer valid
- Fixes: #793
=> Fixed editor hanging when symbolic link path is no longer valid

XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/manifest.json, XRTK-Core/Packages/packages-lock.json, XRTK-Core/ProjectSettings/ProjectVersion.txt
updated project to 2019.4.21f1
=> updated project to 2019.4.21f1

README.md
Adds a badge to the readme displaying the currently online users count in the XRTK discord. Clicking it opens the discord invitation link.
=> Add Discord badge with online user count to readme

XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/manifest.json, XRTK-Core/Packages/packages-lock.json, XRTK-Core/ProjectSettings/ProjectVersion.txt
Updated project to 2019.4.23f1
=> updated project editor to 2019.4.23f1

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Packages/com.xrtk.core/package.json
- delete any meta files for the symlink_temp text files if they happen to get created
- bumped package number
=> More symlink fixes

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/BaseController.cs, XRTK-Core/Packages/packages-lock.json
- Updated all the submodule version dependencies
- Fixed a always null warning in BaseController
- Changed some logs from warnings to info
=> a bit of cleanup for the release

XRTK-Core/Packages/com.xrtk.core/package.json, XRTK-Core/Packages/manifest.json, XRTK-Core/Packages/packages-lock.json
Removed the minimum unity release version for all XRTK projects. Any version of Unity 2019.4.X should be compatible.
=> removed the min unity release rule

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs
Fixed configuration profile picker
- Fixes: https://github.com/XRTK/XRTK-Core/issues/811
=> Fixed configuration profile picker

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Added GetServiceAsycn
- Updated documentation around service and system utilities
- Added `GetServiceAsync<T>()`
=> Updated documentation around service and system utilities

XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityEditorSettings.cs, XRTK-Core/Packages/com.xrtk.core/Editor/XRTK.Editor.asmdef
Import Text Mesh Pro Essential Resources.
Especially helpful for batch mode building bc we don't check in the TMPro assets into source control.
=> Import Text Mesh Pro Essential Resources

XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/BuildDeployWindow.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/BuildInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/IBuildInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UnityPlayerBuildTools.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UwpAppxBuildTools.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UwpPlayerBuildTools.cs, XRTK-Core/ProjectSettings/ProjectSettings.asset
Added `-version`, `-versionCode`, and `-bundleIdentifier` to command line arguments for better flexibility in CI/CD
=> Added additional command line parameters for CI/CD

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/SystemNumericsExtensions.cs
Cherry picked changes from [#815](https://github.com/XRTK/XRTK-Core/pull/815/files#diff-304d2ae7d4c29ee243c40218aa452ebed77eb20f591e0efc4b6ba361ffa320fe)
=> updated system numerics extensions

XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/BuildDeployWindow.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/UnityPlayerBuildTools.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityToolkitRootProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Platforms/BasePlatform.cs
Fixed equality checking on platform types
=> Fixed equality checks for platforms

XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/AndroidBuildInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/UnityPlayerBuildTools.cs
- fixed post process build event forwarder
- updated android build info with manifest stubs
- updated oculus submodule
=> Fixed post process build event forwarder

XRTK-Core/Packages/com.xrtk.core/Editor/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/AssemblyInfo.cs.meta, XRTK-Core/Packages/com.xrtk.core/Runtime/AssemblyInfo.cs
Adding compiler definitions for platforms
- https://github.com/XRTK/ARCore/pull/11
- https://github.com/XRTK/WindowsMixedReality/pull/139
- https://github.com/XRTK/Ultraleap/pull/22
- https://github.com/XRTK/SteamVR/pull/22
- https://github.com/XRTK/SDK/pull/239
- https://github.com/XRTK/Oculus/pull/117
- https://github.com/XRTK/Nreal/pull/16
- https://github.com/XRTK/Lumin/pull/111
- https://github.com/XRTK/Lenovo/pull/10
- https://github.com/XRTK/glTF/pull/9
- https://github.com/XRTK/Etee/pull/9
=> Adding compiler definitions for platforms

XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/NetworkingSystem/IMixedRealityNetworkDataProvider.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/NetworkingSystem/IMixedRealityNetworkingSystem.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Services/NetworkingSystem/MixedRealityNetworkingSystem.cs
updated license headers for networking system
Added ability to check if device is online to the `IMixedRealityNetworkingSystem`
- Fixes: https://github.com/XRTK/XRTK-Core/issues/682
=> Added ability to check if device is online

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityPreferences.cs, XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GitUtilities.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityServiceWizard.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLink.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinkerWindow.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/StringExtensions.cs
Back slash and forward slash string extensions were inverted, needed to be fixed.
- https://github.com/XRTK/Lumin/pull/112
- https://github.com/XRTK/Oculus/pull/118
- https://github.com/XRTK/SDK/pull/240
- https://github.com/XRTK/WindowsMixedReality/pull/140
=> Fixed string extensions (backslahses and forward slashes were inverted)

XRTK-Core/ProjectSettings/GraphicsSettings.asset, XRTK-Core/ProjectSettings/ProjectSettings.asset, XRTK-Core/ProjectSettings/ProjectVersion.txt
=> Updated editor to 2019.4.27f1

XRTK-Core/Packages/com.xrtk.core/Editor/Data/ConfigurationProperty.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Data/ConfigurationProperty.cs.meta, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityPlatformServiceConfigurationProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityServiceProviderProfileInspector.cs, XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/PlatformEntryPropertyDrawer.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/SystemType.cs
Cleaned up and simplified configuration serialized properties a bit.
=> cleaned up service configuration profiles a bit

XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/AssemblyInfo.cs.meta, XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AssemblyDefinitionPreProcessor.cs, XRTK-Core/Packages/com.xrtk.core/Tests/AssemblyInfo.cs, XRTK-Core/Packages/com.xrtk.core/Tests/AssemblyInfo.cs.meta
- Creates `AssemblyInfo.cs` if they didn't exist for each `.asmdef` in the package
- Updates all assembly infos in the package instead of just to two predefined ones
=> Updated AssemblyDefinitionPreProcessor.cs

XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs, XRTK-Core/Packages/manifest.json
- Fixes: an improper platform override when in editor and a different active platform is specified
=> Fixed platform override in editor when a different active platform is specified

XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/XRTK.Editor.BuildPipeline.asmdef, XRTK-Core/Packages/com.xrtk.core/Editor/XRTK.Editor.asmdef, XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/ComponentExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Async/AwaiterExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/WebRequestRest/Rest.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/XRTK.asmdef, XRTK-Core/Packages/com.xrtk.core/Tests/Services/XRTK.Tests.Services.asmdef, XRTK-Core/Packages/com.xrtk.core/Tests/XRTK.Tests.asmdef, XRTK-Core/Packages/com.xrtk.core/package.json
- Added `Rest.DownloadFileAsync()` to download files to disk with the rest utilities
- Updated awaiter extensions with a way to utilize the extension without needing to initialize the xrtk
- Updated awaiter extension with a way to run coroutines with the editor coroutine utilities.
- Added `Component.Validate()` extension method to validate component references.
- Added `Component.SetActive(bool isActive)` extension method to enable/disable a GameObject the Component is attached to.
=> Updated misc extension methods and utiltities

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/StringExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Async/AwaiterExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/WebRequestRest/Rest.cs
- improved rest utilities with a file cache system
- fixed coroutine object assignment
=> Fixed coroutine runner and updated rest utiltitles 

XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/WebRequestRest/Rest.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/XRTK.asmdef, XRTK-Core/Packages/com.xrtk.core/package.json
- added `TryDeleteCachedItem`
- added better bundle caching
- added better progress handling
=> Rest Utilities Update (Caching)

XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs
Updated the Root inspector to update the page when the profile changes
- Fixes: #874
=> Updated the Root inspector to update the page when the profile changes

XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Check if directory exists before creating it.
=> Fix IOException when attempting to create profiles directory in package installer

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/StringExtensions.cs, XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Async/AwaiterExtensions.cs
Fixed string extensions to properly change directory characters when evaluating
Helps fix https://github.com/XRTK/glTF/issues/14
- https://github.com/XRTK/glTF/pull/15
=> Added extension methods to run async code synchronously

docs/articles/appendices/A02-ChoosingXRTKvsMRTK.html
Some documentation information was not up to date, source: https://docs.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/
=> Documentation: Update to the MRTK comparison table

XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/ComponentExtensions.cs
=> Fix Component.SetActive extension

XRTK-Core/Packages/manifest.json
Updated submodules from recent check-ins
- SDK updated
- Spatial Persistence updated
- Updated dependencies in the XRTK-Core project
=> Updated submodules from recent check-ins

XRTK-Core/Packages/com.xrtk.core/Editor/BuildPipeline/AndroidBuildInfo.cs
added the ability to split android apks into expansion files
=> added the ability to split android apks into expansion files

.github/workflows/build.yml
Prevents removed submodules from killing build
=> updated build steps to clean .git folder between each run
